<?php

declare(strict_types=1);

$adminLoginPath = trim((string) getenv('ADMIN_LOGIN_PATH'));
if (preg_match('#^/[A-Za-z0-9/_-]{8,120}$#', $adminLoginPath) !== 1) {
    $adminLoginPath = '/control-room/entry-9d4f';
}
$adminLoginPath = rtrim($adminLoginPath, '/');

return [
    'Public/Landing' => ['title'=>'Landing','path'=>'/','methods'=>'GET','role'=>'guest','service'=>'catalog-service','status'=>'implemented'],
    'Public/About' => ['title'=>'About','path'=>'/about','methods'=>'GET','role'=>'guest','service'=>'none','status'=>'implemented'],
    'Public/Contact' => ['title'=>'Contact','path'=>'/contact','methods'=>'GET|POST','role'=>'guest','service'=>'notification-service','status'=>'implemented'],
    'Public/Faq' => ['title'=>'FAQ','path'=>'/faq','methods'=>'GET','role'=>'guest','service'=>'none','status'=>'implemented'],
    'Public/Courses' => ['title'=>'Courses','path'=>'/courses','methods'=>'GET','role'=>'guest','service'=>'catalog-service','status'=>'implemented'],
    'Public/CourseDetails' => ['title'=>'Course details','path'=>'/course','methods'=>'GET','role'=>'guest','service'=>'catalog-service','status'=>'implemented'],
    'Public/CourseSearch' => ['title'=>'Course search','path'=>'/search','methods'=>'GET','role'=>'guest','service'=>'catalog-service','status'=>'implemented'],
    'Public/Login' => ['title'=>'Choose portal','path'=>'/login','methods'=>'GET','role'=>'guest','service'=>'identity-service','status'=>'implemented'],
    'Public/StudentRegistration' => ['title'=>'Student registration','path'=>'/register/student','methods'=>'GET|POST','role'=>'guest','service'=>'identity-service','status'=>'implemented'],
    'Public/InstructorRegistration' => ['title'=>'Instructor registration','path'=>'/register/instructor','methods'=>'GET|POST','role'=>'guest','service'=>'identity-service','status'=>'implemented'],
    'Public/ForgotPassword' => ['title'=>'Forgot password','path'=>'/forgot-password','methods'=>'GET|POST','role'=>'guest','service'=>'identity-service','status'=>'implemented'],
    'Public/ResetPassword' => ['title'=>'Reset password','path'=>'/reset-password','methods'=>'GET|POST','role'=>'guest','service'=>'identity-service','status'=>'implemented'],
    'Public/VerifyOtp' => ['title'=>'Verify OTP','path'=>'/verify-otp','methods'=>'GET|POST','role'=>'guest','service'=>'identity-service','status'=>'implemented'],
    'Public/PrivacyPolicy' => ['title'=>'Privacy policy','path'=>'/privacy','methods'=>'GET','role'=>'guest','service'=>'none','status'=>'planned'],
    'Public/TermsAndConditions' => ['title'=>'Terms and conditions','path'=>'/terms','methods'=>'GET','role'=>'guest','service'=>'none','status'=>'planned'],
    'Public/OAuth' => ['title'=>'OAuth','path'=>'/oauth','methods'=>'GET','role'=>'guest','service'=>'identity-service','status'=>'planned'],
    'Public/Logout' => ['title'=>'Sign out','path'=>'/logout','methods'=>'POST','role'=>'guest','service'=>'identity-service','status'=>'implemented','room_files'=>['Middleware.php','Controller.php']],

    'Student/Login' => ['title'=>'Student sign in','path'=>'/learn/sign-in','methods'=>'GET|POST','role'=>'guest','service'=>'identity-service','status'=>'implemented','middleware_file'=>'StudentGuestGate.php','controller_file'=>'StudentLoginAction.php','room_files'=>['StudentEntryRoute.php','StudentGuestGate.php','StudentCredentialPacket.php','StudentIdentityBridge.php','StudentLoginAction.php','StudentLoginScreen.php','ROOM.md','Components/README.md','Assets/page.css','Assets/page.js','Tests/README.md']],
    'Student/Registration' => ['title'=>'Student registration','path'=>'/student/register','methods'=>'GET|POST','role'=>'guest','service'=>'identity-service','status'=>'implemented'],
    'Student/Dashboard' => ['title'=>'Student dashboard','path'=>'/student/dashboard','methods'=>'GET','role'=>'student','service'=>'reporting-service','status'=>'implemented'],
    'Student/Cart' => ['title'=>'Cart','path'=>'/student/cart','methods'=>'GET|POST','role'=>'student','service'=>'commerce-service','status'=>'implemented'],
    'Student/Checkout' => ['title'=>'Checkout','path'=>'/student/checkout','methods'=>'GET|POST','role'=>'student','service'=>'commerce-service','status'=>'implemented'],
    'Student/Payment' => ['title'=>'Payment','path'=>'/student/payment','methods'=>'GET|POST','role'=>'student','service'=>'payment-service','status'=>'implemented'],
    'Student/PaymentHistory' => ['title'=>'Payment history','path'=>'/student/payment-history','methods'=>'GET','role'=>'student','service'=>'payment-service','status'=>'implemented'],
    'Student/MyCourses' => ['title'=>'My courses','path'=>'/student/my-courses','methods'=>'GET','role'=>'student','service'=>'enrollment-service','status'=>'implemented'],
    'Student/CoursePlayer' => ['title'=>'Course player','path'=>'/student/course-player','methods'=>'GET','role'=>'student','service'=>'learning-service','status'=>'implemented'],
    'Student/Progress' => ['title'=>'Progress','path'=>'/student/progress','methods'=>'GET|POST','role'=>'student','service'=>'learning-service','status'=>'implemented'],
    'Student/Notifications' => ['title'=>'Notifications','path'=>'/student/notifications','methods'=>'GET|POST','role'=>'student','service'=>'notification-service','status'=>'implemented'],
    'Student/Profile' => ['title'=>'Profile','path'=>'/student/profile','methods'=>'GET|POST','role'=>'student','service'=>'identity-service','status'=>'implemented'],
    'Student/Unsubscribe' => ['title'=>'Unsubscribe request','path'=>'/student/unsubscribe','methods'=>'GET|POST','role'=>'student','service'=>'enrollment-service','status'=>'implemented'],
    'Student/Reviews' => ['title'=>'Reviews','path'=>'/student/reviews','methods'=>'GET|POST','role'=>'student','service'=>'review-service','status'=>'implemented'],

    'Instructor/Login' => ['title'=>'Instructor studio access','path'=>'/teach/studio-access','methods'=>'GET|POST','role'=>'guest','service'=>'identity-service','status'=>'implemented','middleware_file'=>'StudioGuestCheckpoint.php','controller_file'=>'OpenInstructorStudio.php','room_files'=>['StudioAccessRoute.php','StudioGuestCheckpoint.php','StudioAccessRequest.php','InstructorStudioGateway.php','OpenInstructorStudio.php','StudioAccessScreen.php','ROOM.md','Components/README.md','Assets/page.css','Assets/page.js','Tests/README.md']],
    'Instructor/Registration' => ['title'=>'Instructor registration','path'=>'/instructor/register','methods'=>'GET|POST','role'=>'guest','service'=>'identity-service','status'=>'implemented'],
    'Instructor/VerificationPending' => ['title'=>'Verification pending','path'=>'/instructor/verification-pending','methods'=>'GET','role'=>'instructor','service'=>'identity-service','status'=>'implemented'],
    'Instructor/Dashboard' => ['title'=>'Instructor dashboard','path'=>'/instructor/dashboard','methods'=>'GET','role'=>'instructor','service'=>'reporting-service','status'=>'implemented'],
    'Instructor/MyCourses' => ['title'=>'My courses','path'=>'/instructor/courses','methods'=>'GET|POST','role'=>'instructor','service'=>'catalog-service','status'=>'implemented'],
    'Instructor/CreateCourse' => ['title'=>'Create course','path'=>'/instructor/courses/create','methods'=>'GET|POST','role'=>'instructor','service'=>'catalog-service','status'=>'implemented'],
    'Instructor/EditCourse' => ['title'=>'Edit course','path'=>'/instructor/courses/edit','methods'=>'GET|POST','role'=>'instructor','service'=>'catalog-service','status'=>'implemented'],
    'Instructor/CurriculumBuilder' => ['title'=>'Curriculum builder','path'=>'/instructor/curriculum','methods'=>'GET|POST','role'=>'instructor','service'=>'learning-service','status'=>'planned'],
    'Instructor/Lessons' => ['title'=>'Lessons','path'=>'/instructor/lessons','methods'=>'GET|POST','role'=>'instructor','service'=>'learning-service','status'=>'implemented'],
    'Instructor/DraftCourses' => ['title'=>'Draft courses','path'=>'/instructor/courses/drafts','methods'=>'GET','role'=>'instructor','service'=>'catalog-service','status'=>'planned'],
    'Instructor/PendingCourses' => ['title'=>'Pending courses','path'=>'/instructor/courses/pending','methods'=>'GET','role'=>'instructor','service'=>'catalog-service','status'=>'planned'],
    'Instructor/PublishedCourses' => ['title'=>'Published courses','path'=>'/instructor/courses/published','methods'=>'GET','role'=>'instructor','service'=>'catalog-service','status'=>'planned'],
    'Instructor/Students' => ['title'=>'Students','path'=>'/instructor/students','methods'=>'GET','role'=>'instructor','service'=>'enrollment-service','status'=>'implemented'],
    'Instructor/Sales' => ['title'=>'Sales','path'=>'/instructor/sales','methods'=>'GET','role'=>'instructor','service'=>'reporting-service','status'=>'planned'],
    'Instructor/Coupons' => ['title'=>'Coupons','path'=>'/instructor/coupons','methods'=>'GET|POST','role'=>'instructor','service'=>'commerce-service','status'=>'implemented'],
    'Instructor/BankDetails' => ['title'=>'Bank details','path'=>'/instructor/bank-details','methods'=>'GET|POST','role'=>'instructor','service'=>'payment-service','status'=>'implemented'],
    'Instructor/Withdrawals' => ['title'=>'Withdrawals','path'=>'/instructor/withdrawals','methods'=>'GET|POST','role'=>'instructor','service'=>'reporting-service','status'=>'implemented'],
    'Instructor/Notifications' => ['title'=>'Notifications','path'=>'/instructor/notifications','methods'=>'GET|POST','role'=>'instructor','service'=>'notification-service','status'=>'planned'],
    'Instructor/Messaging' => ['title'=>'Messaging','path'=>'/instructor/messaging','methods'=>'GET|POST','role'=>'instructor','service'=>'notification-service','status'=>'planned'],
    'Instructor/Profile' => ['title'=>'Profile','path'=>'/instructor/profile','methods'=>'GET|POST','role'=>'instructor','service'=>'identity-service','status'=>'implemented'],

    'Admin/Login' => ['title'=>'Restricted control entry','path'=>$adminLoginPath,'methods'=>'GET|POST','role'=>'guest','service'=>'identity-service','status'=>'implemented','middleware_file'=>'AdminEntryGate.php','controller_file'=>'EnterControlRoom.php','room_files'=>['ControlRoomRoute.php','AdminEntryGate.php','AdminChallengeEnvelope.php','AdminIdentityChannel.php','EnterControlRoom.php','ControlRoomScreen.php','ROOM.md','Components/README.md','Assets/page.css','Assets/page.js','Tests/README.md']],
    'Admin/Dashboard' => ['title'=>'Admin dashboard','path'=>'/admin/dashboard','methods'=>'GET','role'=>'admin','service'=>'reporting-service','status'=>'implemented'],
    'Admin/InstructorApprovals' => ['title'=>'Instructor approvals','path'=>'/admin/instructor-approvals','methods'=>'GET|POST','role'=>'admin','service'=>'identity-service','status'=>'implemented'],
    'Admin/CourseApprovals' => ['title'=>'Course approvals','path'=>'/admin/course-approvals','methods'=>'GET|POST','role'=>'admin','service'=>'catalog-service','status'=>'implemented'],
    'Admin/Students' => ['title'=>'Students','path'=>'/admin/students','methods'=>'GET|POST','role'=>'admin','service'=>'identity-service','status'=>'implemented'],
    'Admin/Instructors' => ['title'=>'Instructors','path'=>'/admin/instructors','methods'=>'GET|POST','role'=>'admin','service'=>'identity-service','status'=>'implemented'],
    'Admin/Users' => ['title'=>'Users','path'=>'/admin/users','methods'=>'GET|POST','role'=>'admin','service'=>'identity-service','status'=>'implemented'],
    'Admin/Enrollments' => ['title'=>'Enrollments','path'=>'/admin/enrollments','methods'=>'GET|POST','role'=>'admin','service'=>'enrollment-service','status'=>'implemented'],
    'Admin/Orders' => ['title'=>'Orders','path'=>'/admin/orders','methods'=>'GET|POST','role'=>'admin','service'=>'commerce-service','status'=>'implemented'],
    'Admin/Payments' => ['title'=>'Payments','path'=>'/admin/payments','methods'=>'GET|POST','role'=>'admin','service'=>'payment-service','status'=>'implemented'],
    'Admin/Refunds' => ['title'=>'Refunds','path'=>'/admin/refunds','methods'=>'GET|POST','role'=>'admin','service'=>'payment-service','status'=>'planned'],
    'Admin/Withdrawals' => ['title'=>'Withdrawals','path'=>'/admin/withdrawals','methods'=>'GET|POST','role'=>'admin','service'=>'reporting-service','status'=>'planned'],
    'Admin/Categories' => ['title'=>'Categories','path'=>'/admin/categories','methods'=>'GET|POST','role'=>'admin','service'=>'catalog-service','status'=>'implemented'],
    'Admin/Coupons' => ['title'=>'Coupons','path'=>'/admin/coupons','methods'=>'GET|POST','role'=>'admin','service'=>'commerce-service','status'=>'implemented'],
    'Admin/Reports' => ['title'=>'Reports','path'=>'/admin/reports','methods'=>'GET','role'=>'admin','service'=>'reporting-service','status'=>'implemented'],
    'Admin/AuditLogs' => ['title'=>'Audit logs','path'=>'/admin/audit-logs','methods'=>'GET','role'=>'admin','service'=>'reporting-service','status'=>'planned'],
    'Admin/Security' => ['title'=>'Security','path'=>'/admin/security','methods'=>'GET|POST','role'=>'admin','service'=>'identity-service','status'=>'planned'],
    'Admin/Settings' => ['title'=>'Settings','path'=>'/admin/settings','methods'=>'GET|POST','role'=>'admin','service'=>'reporting-service','status'=>'implemented'],
    'Admin/ContactMessages' => ['title'=>'Contact messages','path'=>'/admin/contact-messages','methods'=>'GET|POST','role'=>'admin','service'=>'notification-service','status'=>'implemented'],
    'Admin/Notifications' => ['title'=>'Notifications','path'=>'/admin/notifications','methods'=>'GET|POST','role'=>'admin','service'=>'notification-service','status'=>'planned'],
];
